apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: simple-java-web-app
spec:
  source:
    git:
      url: https://github.com/jrsamson/simpleAccerelator.git
      ref:
        branch: main